// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// Auto-generated by cdm install. Do not edit by hand.
// CDM package: @use-truapi/counter
// CDM version: 1

interface IUseTruapiCounter {
    error InvalidCalldata();
    error CalldataTooLarge();
    error NoSelector();
    error UnknownSelector();
    error NonPayableValueReceived();
    function getCount() external view returns (uint64);
    function increment() external;
    function add(uint64 value) external;
}

library UseTruapiCounter {
    address internal constant ADDRESS = 0x5cc9CAa3f241e02c63c4B0431DB1239Bc0649CC1;

    function ref() internal pure returns (IUseTruapiCounter) {
        return IUseTruapiCounter(ADDRESS);
    }

    function cdm() internal pure returns (IUseTruapiCounter) {
        return ref();
    }
}
