import type { HostChainIdentifier } from "@parity/product-sdk-host";
import type { ChainDefinition } from "polkadot-api";

export type { HostChainIdentifier };

export interface ChainConfig<D extends ChainDefinition = ChainDefinition> {
  /** PAPI descriptor generated by `papi add` (or from `@parity/product-sdk-descriptors/*`). */
  descriptor: D;
  /**
   * Genesis hash the host is asked to serve. Optional when `hostChain` is set:
   * inside a host the hash is then discovered from the host's environment
   * (RFC-0026) and this value is only the fallback for hosts that predate
   * discovery. Standalone the WebSocket provider reads it from the node.
   */
  genesisHash?: `0x${string}`;
  /**
   * RFC-0026 chain role (`"Relay" | "AssetHub" | "People" | "Bulletin"`).
   * Resolved against the host's configured network at connect time, so the
   * config survives testnet resets that change the genesis hash.
   */
  hostChain?: HostChainIdentifier;
  /**
   * WebSocket RPC endpoints used when the app runs outside a Polkadot host
   * (standalone dev in a plain browser tab). Inside a host the chain
   * connection is always routed through the host provider.
   */
  wsUrls?: string[];
}

export type AnyChains = Record<string, ChainConfig>;

export interface ProductAccountConfig {
  /**
   * DotNS identifier of the deployed product, e.g. `"my-app.dot"`. Omit to
   * take the canonical id from the host's product context (`getProductContext`)
   * and fall back to `<dappName>.dot` on hosts that predate it.
   */
  dotNsIdentifier?: string;
  derivationIndex?: number;
  /**
   * Whether connecting should also resolve the user's DotNS username.
   * Triggers an identity permission prompt in the host — default false.
   */
  requestName?: boolean;
}

export interface StatementsConfig {
  /** App namespace: all statements are tagged with `blake2b(appName)`. */
  appName: string;
  defaultTtlSeconds?: number;
}

export interface CloudStorageConfig {
  environment: "paseo" | "previewnet" | "devnet";
}

export interface TruapiConfig<TChains extends AnyChains = AnyChains> {
  chains: TChains;
  /** Chain used when a hook doesn't specify one. Defaults to the first key of `chains`. */
  defaultChain?: keyof TChains & string;
  /** Shown by host wallets in signing prompts. */
  dappName?: string;
  productAccount?: ProductAccountConfig;
  statements?: StatementsConfig;
  cloudStorage?: CloudStorageConfig;
  /** Connect the signer as soon as the runtime is created. Default false. */
  autoConnect?: boolean;
  /** Cap on host chain-provider acquisition; a dead host channel otherwise hangs forever. */
  hostProviderTimeoutMs?: number;
}

/** Identity helper that preserves the precise chain map type for typed hooks. */
export function defineConfig<const TChains extends AnyChains>(
  config: TruapiConfig<TChains>,
): TruapiConfig<TChains> {
  const entries = Object.entries(config.chains);
  if (entries.length === 0) {
    throw new Error("use-truapi: config.chains must contain at least one chain");
  }
  for (const [key, chain] of entries) {
    if (!chain.genesisHash && !chain.hostChain) {
      throw new Error(
        `use-truapi: chain "${key}" needs a genesisHash or a hostChain role so the host knows which chain to serve`,
      );
    }
  }
  return config;
}

export function resolveChain<TChains extends AnyChains>(
  config: TruapiConfig<TChains>,
  chain?: keyof TChains & string,
): { key: keyof TChains & string; chain: ChainConfig } {
  const key =
    chain ?? config.defaultChain ?? (Object.keys(config.chains)[0] as keyof TChains & string);
  const resolved = config.chains[key];
  if (!resolved) {
    throw new Error(
      `use-truapi: unknown chain "${String(key)}" — configured: ${Object.keys(config.chains).join(", ")}`,
    );
  }
  return { key, chain: resolved };
}
